name: Pazudis pirmkodā
description: Meklējot jaunus veidus, kā uzspridzināt savu datoru
meta_description: "Meklējot jaunus veidus, kā uzspridzināt savu datoru"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: '/'
domain_name: "http://pirmkods.arseniuss.id.lv"
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://pirmkods.arseniuss.id.lv'
author:         'Armands Arseniuss Skolmeisters'
